"""first

Revision ID: 8f85e5a9f164
Revises: 35ea78dc450c
Create Date: 2023-07-14 13:59:04.293325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f85e5a9f164'
down_revision = '35ea78dc450c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cargo_type', sa.Enum('glass', 'other', name='cargotypes'), nullable=False),
    sa.Column('rate', sa.DECIMAL(precision=18, scale=5), nullable=True),
    sa.PrimaryKeyConstraint('date', 'cargo_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance')
    # ### end Alembic commands ###
